### ISSUE TITLE
Spectral and temporal shape analogy

### ISSUE THREAD

**Issue by koesterf** [LASY-org/lasy#286]
Hi, 

I constructed the laser pulse using a temporal signal for longitudinal profile.
 
After constructing a laser pulse, is it possible to get the spectral information of the pulse directly from LASY ?

For example, is it possible to get a three column data file with:

(1) First column representing the "laser wavelength",
(2) Second column representing the corresponding "spectral intensity", and
(3) Third column representing the corresponding "spectral phase".

Thanks a lot.

**Comment by koesterf** [comment]
Hi, 

what is is the use of "get_spectral_field()"  unitility [here](https://lasydoc.readthedocs.io/en/latest/api/utils/grid.html#lasy.utils.grid.Grid.get_spectral_field)

**Comment by n01r** [comment]
The `get_spectral_field()` entered the mainline last month with https://github.com/LASY-org/lasy/commit/350059b7b55520f98b2824c6b190618b42a8a870.

From what I could see (after I upgraded my LASY to `0.5.0` via `python -m pip install --upgrade`), when you have a `laser` object you can do `laser.grid.get_spectral_field` which gives you the complex representation of the laser field in spectral space.

I had to do a `fftshift` on it because the signal was still at the edges of the domain, rather than in the center.
Perhaps, @RemiLehe can answer in more detail how you would best get to the data you are interested in.

**Comment by koesterf** [comment]
Hi @n01r, thanks for answering. I hope this utility will be useful. I hope that the documentation will be improved a lot with sufficient example to show the use of such useful functions. 

I had bring to the notice of ( @RemiLehe ) the issue I am facing regarding porting LASY generated file into FBPIC [#285](https://github.com/LASY-org/lasy/issues/285). I really want to explore and use the powerful features of LASY.

**Comment by n01r** [comment]
Hi @koesterf, thanks a lot for bringing this to our attention!
It's always good if people open issues about the things they struggle with using open-source software.
We will try to improve examples and documentation continuously.

It is invaluable, to have users who are particularly interested in a specific use case because as they learn how to model what they want to model, and developers learn what features and documentation are missing, the findings can immediately be shared with the community.

Hopefully, we can figure out together how to enable the functionality you are looking for. Please feel invited :sparkles:  and empowered :muscle: to open a pull request yourself, too, and contribute your insights if you feel the documentation could be improved. :slightly_smiling_face:

**Comment by RemiLehe** [comment]
Thanks for the question @koesterf. Currently, `lasy` does not support outputting the spectral information of a pulse.

Regarding the function `get_spectral_field`: this function is meant to be used internally inside the `lasy` package. It was not meant to be exposed to the user directly. I will remove it from the online documentation.

**Comment by RemiLehe** [comment]
More generally, I think we need to be careful about which feature we add in `lasy` (e.g. such as analyzing spectral data).
There is a fine balance in keeping `lasy` focused on its main function (i.e. initializing complex laser, and saving them in a format that PIC code can easily read) and the aim of `lasy` is not to become a laser analysis tool. (It would make more sense to have this in post-processing tools, such as `openPMD-viewer`.)
That being said, we welcome those feature requests, and will consider in which part of the BLAST ecosystem they should be added.

**Comment by koesterf** [comment]
Hi @RemiLehe thank you for explanation. If possible, let us see (with the help of users suggestions) how to make the documentation more self explanatory. The users will surely participate.
